### ISSUE TITLE
[FEATURE REQUEST] Implementation for DNS enabled host record

### ISSUE THREAD

**Issue by doubletwist13** [gomorpheus/morpheus-infoblox-plugin#9]
Need to be able to use DNS enabled host records `configure_for_dns: true` rather than the separate creation of DNS records.

It looks like there's already a pull request (https://github.com/gomorpheus/morpheus-infoblox-plugin/pull/7) that implements exactly what is needed which has been sitting around since January.

**Comment by BungeBash** [comment]
versions 1.2.6 and 1.4.0 should include this functionality. Running through QA
